---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    template:
      data:
        HEARTBEAT_URL: "{{ .HEARTBEAT_URL }}"
        PUSHOVER_TOKEN: "{{ .TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .USER_KEY }}"
  dataFrom:
    - extract:
        key: healthchecks
    - extract:
        key: pushover
