apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  ALERTMANAGER_HEARTBEAT_URL: ENC[AES256_GCM,data:VMiEicW3wYKOnQHVamLBo/ksTN8QKCXozgP4Otnq0mEAUbj/I1sIjNywyamq0U0tqD+dAwu1fco=,iv:GBi9b/O4zmgww50PmGTFIkQi0/JFfzhGz8mVYz9YGSA=,tag:z4d0MA7YfKh9tVL+PjhZSQ==,type:str]
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:B0G8ElpJ0r9VZy/1ievCWSEyXgHxYd/UVNAcKPme,iv:29yeZeKQZOFvVoxKz/oe5ZvSK4KaSkIlV7zUj6gJCVI=,tag:TBd3jGKiEtmQrnQeQuJIyA==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:YgVebnipuOeYpWuoP9p2bDvyM9+LHebzKOAoWDmw,iv:m+E/WkESjBEi/5t8mWRjabYMPAYXX4lkuBWOcI4uthw=,tag:zPOE+zX5pSxKB3kpbmOf2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZlVUenBic3p1Nis0ZjI1
        SnVWTVB4V2Rja0gyRzJIVXdmaXZSL08xNkNBCnMvZGNXdUIyRGpOTXZSVyt5SU1D
        bys2dW0vakdyQU0wcHEzdW13dUpUU28KLS0tIDIwVzI2RkJETE1hVFg1aXJ6b2Jk
        My80WWxoNFY0QTJ0OHdNcWZyZlBGV1kKnwGa/RPV7GZigpwupJQh71I23oO8TgNm
        TgBqzuJaJxNrCcqKvGcFTvLb2DTEVNbHucBUoX9uq6rG4joLuWO2eg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T23:14:58Z"
  mac: ENC[AES256_GCM,data:PiJT37XyAvtCvlUKZ7B2zozd4jXq+dcXdGYfy16aUqh+NTWUJId5/0IDjoRg3cgMrzI+UHOentwaoFui3EenL/sTXnNIrfMW5DaDP41i+OgD2gEpBt7Nn3lDqylpjRW4qhGp/hVPiqfWlyFZ4uwVWD021/fQZiX/1JkIXm0owis=,iv:wVKb7wq+2cw7yZMUvOoczPT/NKtqm8liCtPJG3KfVHY=,tag:7VMt7OQnuRNLNsYZiu66Mw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
