---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops
  - ../../components/kopiur/secret

resources:
  - ./namespace.yaml
  - ./limitrange.yaml
  - ./jellyfin/ks.yaml
  - ./qbittorrent/ks.yaml
