apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:zh404lwYA9bnovL6SK2JL5WR37jZEjE8lo0ck4DH4qYUytLeriqIF86NfEv285rewA8Tha8=,iv:kHRzGHYZEiAxAfr2W+AiUvUdjc5K3yn+xjFPHuL+4K4=,tag:zl6oFwH4ouOj8tOvFbaKaA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOTRXemlOMkw0aCtrSWhW
        NU1BRU5PbjB3bFdnb1lKT0FNTC9YanphWTNjCnRleEYzZEF5a01ndDAwY0RGdkpB
        aEltcm0xU1ZtSmp3UC9VODBZeGJoNk0KLS0tIFc4eTJBRzJxOHFzNUUwcExLR2F0
        Y2xZTUl0aTZWQnBwVSt5SFpKRzJBNU0KoewRHY+/cW278eMyW62hGDMAzia7JaYi
        vydxwkJ6DHRJ6AbqKOYI0kW8qqmL6y5sradalYL8Zke5pdg6/10M0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T18:52:39Z"
  mac: ENC[AES256_GCM,data:DzqsLc2gSgAq6a78Sh0ndGjr34ZYJhkwLSFgsnMN7mFJVtD9YaMaCv3dciagxaecoZkjkr5KgiMZnyxjnOjo0Vc6iUXyaU3akNBP2Rmu8lVvz0WkSw5ui7GAhNPbKxh18+aKUqFNB2etP0dblmEsAYivrQX9nFV8SmwnSjg4Nrw=,iv:uuAgg9KpGTrRuO+F03Fhw1w6riy6M+vGjR7mblL5flM=,tag:jk/+2oaDOyshVx26XilWdg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
