---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              limits:
                cpu: 8000m
                memory: 6144Mi
              requests:
                cpu: 400m
                memory: 6144Mi
              claims:
                - name: gpu
    defaultPodOptions:
      automountServiceAccountToken: false
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: jellyfin-gpu
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      config-old:
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config-old
      media:
        enabled: true
        type: nfs
        server: 172.16.69.17
        path: /volume1/media
        advancedMounts:
          jellyfin:
            app:
              - path: /media
                readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /cache/images
                subPath: images
              - path: /cache/transcodes
                subPath: transcodes
              - path: /config/log
                subPath: log
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - jellyfin.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    service:
      app:
        ports:
          http:
            port: *port
