apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:j9ljN+loncT7,iv:TmieyQpJKCdJmAM41vCgRx46mgqoa/mdMtX53HRhmlM=,tag:pIGsNwvCxI90tAKGyKvefA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSmwxVFNReE55SE1ucjNQ
        UEo3Zzg0ZnNiczg5ZXlmZGRCNTRXa3pKaEdnCkNjN2Z6VDlXckU0YkZTaXFkQzYr
        ZG1Jb3d4Tm5JaEM2NExlT2J2am9BTEEKLS0tIHZ3WDEyWWRkd0FKeTVHTDhHNDZo
        SDZKYlRTcnNqTGZjT2VvWWlpejlkZ1EKKhCrYMhQoGB89FU/G4+bb1+coSZnX/Q6
        NR4YW81XHbrRtnPVTclTmuCNStHaZLKivxtvajokYhviN6PHXwE5mg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T18:52:39Z"
  mac: ENC[AES256_GCM,data:h9Lt0sBCs0xfyFiWPBIxH87F8BGVT5PEN+v/PBd37mjzTHN5rQi7OaQU7DML/cOE0iIqJ0UG39TjZcSydI27chXhyNjfXc4T7w4sItd/q2R9jNd2Nzkb+DRBV7J+foWtrRWUEf81vakKaLUm9gXNXvSx7PbPqO8Pa9Mq18cE6vg=,iv:OrgFSZcrUPT9fT/VOD50r58f4pH9ARZDtWPhj4NEeHc=,tag:aOTHUVS8vNWd+R0kXRn2aw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
