apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5E35/vYROGtU,iv:JRGtSI+n4RcOOc1En6r33X9wdJgsZ9Z88v8UGCSZdBQ=,tag:RuOh+GNiYn2Z1+0sqSToKA==,type:str]
  BLACKBOX_IP4_EXTERNAL_ADDRESS: ENC[AES256_GCM,data:P9sKQndo8TXUqiI2,iv:y2M0bzbtnvn5YzgEIahp4JQZx7+pf9pBB0t+ynweuWo=,tag:EIqQ2P5G5v5JbS5zXgI1YA==,type:str]
  BLACKBOX_IP6_EXTERNAL_ADDRESS: ENC[AES256_GCM,data:G9zINQm0+2q+5sQX+Qmn1KeWlhYt/j49FnqeeIt4uRuu+khH,iv:2JmOLxh9uGtEULk7cOzCNTciWGTxM4t+ahCl/LWG3/U=,tag:+6YnxA0gx7pfpcV7m+4WUQ==,type:str]
  BLACKBOX_IP4_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:ZSVkkjoZbsKAsKVJDbTnMB3y,iv:uXAKzmEa41zX8mnVFHHJgYu8OwYu/gXHHQGqDPtkmkM=,tag:qK4BnYKqURbE7sn0xF16XA==,type:str]
  BLACKBOX_IP6_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:brzvxhQvmGiOxpHquB7hCTgU,iv:85FllFIVyyI1jsRmsd9jJM0qGcYXPHkUAJGzRLEKp1A=,tag:EVogpzQcNWZdZUqLYCgwMQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYVhDeCtVeHkvdlgxa0lG
        U0cwZnFVRXo4LzJ6d0xxUmgraVY2U1hnU200CmlyaGdGOHFJRVltUUlTR1EvRng3
        bVhhcmxWdmlnY2sra0FtRVMxUGEvVkEKLS0tIDQyN21YUG1pWlRBQ29DbXMraXRl
        YmtnakxZMFIzMVppaEgrdzk1UEtpK00KBWqlAnTr2ZB7xN+XqUGs4OCfyQvetIRa
        rJWf095D0RF1+KNkJGD1Ha4YxZP1XW05hMejGNCuO7wGuNfB1Py7QA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T15:20:52Z"
  mac: ENC[AES256_GCM,data:26afIAB27FKmUuCFBuMBC/SR4mHvGVPRZA818fGlq6l5hZ7tVXxUQNQKvXpfy/mOvixiAP6IWKNnw26qv/wQuyA51GMt1UXpLYqYo5XyOv0CdbieD9V6cIdRCvobXCkc8gm7t95Hz2LhzQsXQb2YdGOOisZOlD9bHf8YHxaATGs=,iv:FqXWnojnzdgwvb8MpsIdKD3xXjxpqChKN8nYoP1yxRo=,tag:hbS/kdp3I0ZTD3C3oph9TA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
