apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Emf2Ds9V7v6l,iv:3xN5XW90Yma8vKt9SphDdLNlOJTIy/8I5TJ6FEUOHzE=,tag:ohihU4t1HVwEx5K7dH10Pw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeUJXSW1ZbXRTNlNHaVB4
        aVRHcm54a3drZ2JMRVBGSlNjVkJTaVZodURvCklENEVJZmZnaitVZzIzVlZvOHQ0
        bWEwZjlub1YwQ3psbmE3WTRWdkhPU0kKLS0tIFhjWGkzOFI1MFZhTEVXamVYTjNl
        TU9wWEpWY1dqUEQwZDNKMDRNTEx1ZjgK3WViGg36KhcpV9EtH47Y3pWInUUQPkew
        1edii3nFsP0dAOi3WNiC99vb7ERa98GoMDM2jaQfbp8Zi5SFqijL4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T11:54:55Z"
  mac: ENC[AES256_GCM,data:4+Iuoq7XryR/SOgAC4LrTwscKRePhE0saU8yvvBAwvczhQG6Fqu3R5s75LxnHbIJ+gu+SCQ464+yEQ/XoEO7jU6B+ZLm4U4MK856Zk9FdRenTYNBhCKaShtkn1AdcHLchWfiMjaCP0VXmbFTFwO+J7X4CIQdRY2ihcgOm4+eRQM=,iv:wWFF4dRBopRb2tuggkaRfLdrn1cGyZpAMVdVRNlbZ9Y=,tag:aGuBg37SexyRqZT09Va4Og==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
