apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:vAOXhtuzVURiUbZYEWkTvDIU9c0sXnXDA7Nf4TKah0E=,iv:x6pO2BfVbsd1/DDYbjAu3Q2DZk3NdAwngs1TtnhdgiI=,tag:b9cUZs2mXroImd7KlfEbVA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY1VOREtvWGdKVVlHZWd5
        eEdiZmpEUWxBNy9KT0JCcTdQQWFjTHE0ZVVNClBKejRZTHZWUW40b2loZGlYWmwy
        UTdTQWpiM0ViNHg5RytNRmF3NDc4OFUKLS0tIEhHa3ZBZmVBQUFWR2NiMy9KQ1Q1
        aXh1cFVYcjR0QmZSb2pncXZhRXBOYmsKOh9yi1YazJ6o5NDBWGyE1R3IwQgNrkrR
        hpWksnoywRKN/vlPBn+uX5Z34TkfbeYkQTxYkiuReJhVsdEfPVn6tg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T18:52:39Z"
  mac: ENC[AES256_GCM,data:sxsp9hBdYKcMQd6w2/dx/QMZe6JvZ4NGlZ2OO1fnDLlevh5H0BlZ8s6DbG/R7pDDBnzNZ5CIgK1dHTfmAkDmt/8KO6ZKA8AO2iwjtuIXb31SW/rcAuOU0vHiPUvw6Ol7g8oaYn4m3QckKlWESkDdcTyHbXZFy+TPvDLJNrDMvfo=,iv:LJ/Y7re3hRvPWTjZTno9OAM76AFH++e10i5LQrX90dY=,tag:kCBuPx9RA0Lp8hjtvwhGNg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
