---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    template:
      data:
        CLOUDFLARE_DNS_API_TOKEN: "{{ .DNS_API_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare
