apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:1zwdy0k1Eqm4rjImt4Tz/Qin6s4m/ba7NIDCKjxNaCtUFetr86crfbY734ZruqGRf3Na2LU=,iv:PsD2VvGlLv5YO72QGWkUcC976xR9tGcVRpxEKR5krZQ=,tag:0Upc8acuqbS1FIx2YPaZrQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNmsvY08zTjhDMEdnYm5H
        MXBCTWd1cytydCs3MlYweXhjaVIxUmxXV2tjCmxOckRQNDNJVThkbWlOT1RkZjVs
        RER2aWNGbTkwUEdiWjhVYW5yNHFocUEKLS0tIFFCUHhKUUJKbndVS25ySWtOUXBX
        WCt0c21pTHdWc3JWWkJHTkNMQnZUcTAKQocUzByE/zgmaCKzkB8Vz+vZ3kmr6ySY
        ajmUcjFq+mJJ7+O4904GdM75NFrJICquR5xBeXBnA8p16ZA/EeXqZg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T13:21:34Z"
  mac: ENC[AES256_GCM,data:wVJWRSPF4TkpVk/iZwgBlQKWVoLX9Kpwp0mlCjUWt5aSC901mlh5yyj6cUxlr/NV6rBTMZh9axR5UpcPXIZyz9SOZajNCLdUoLs/CsuD+CKXIHbXVqbfUPF5BhFth8NA2OIofiveWXxHpedT/6M26Uc8Rmq07BToXKunSfkDepU=,iv:YqV6Ct4ZX0RIkCHvVmfMsF7tyNcPdrzRy3BWsS2aP5E=,tag:imenXe8f78XsqiL69Z9aaA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
