apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:A7aRM5yoQ+YLw4YErOUAviV3JEroXm3rODUuHZk6Mrxh0TIlS3+1pw==,iv:RRRoHgB+pdIt1yxRA4BNoVCtCM2iWpDoKF/9heoTd1c=,tag:cqnvWl25I5waK+UR8zMxVw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSk9HbURMU09CdFd5RGlR
        WTMyY0YyQkQ5VmU5NEt3WVBUZk5yZ2pwQkVrCkt3NW9mYnpmOFNKTFNPTzBLVEQz
        S1c2R0d6VytlN21QaFd2ODhNbTFNalkKLS0tIHlyNDlWTElMWHJnOTNsY3lMRFlI
        T0w0dHJaSFpxdlJ2enBtV1RCbGhSODgK0xQuuPE6V01qU2twqh7rWuJo8aEra4MM
        qOokiPDTBXfbYgRaApKBMXOMl9DlmXyqRFjryRvmF6nkNudbWfrl7A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T23:07:22Z"
  mac: ENC[AES256_GCM,data:vaQRTtuTBJxHQvVxeUsuTGGOielsalZT78ZB7gKE0BP28HXTqE41ZcYtTAyeDI5ggeAV/zrUh/IwEk946V6yuUPedHGntKleyHNpJ73L9pTG9Q8ecDcFg2K5eULK+OhFfqU7gJW4oAKcKVVFFjO1KsGskSSBtnqKyk8lQSF6vNU=,iv:mjAL9Hu8EDVmt0q/qMC7n4aqQ9tGoOFwkOf600ZgHUM=,tag:wo1bpnDmElMlX2WVZeoX3g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
