---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  chartRef:
    kind: OCIRepository
    name: reloader
  interval: 1h
  values:
    fullnameOverride: reloader
    reloader:
      logFormat: json
      logLevel: info
      readOnlyRootFileSystem: true
      podMonitor:
        enabled: true
        namespace: "{{ .Release.Namespace }}"
