---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blackbox-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    template:
      data:
        BLACKBOX_IP4_EXTERNAL_ADDRESS: "{{ .IP4_EXTERNAL_ADDRESS }}"
        BLACKBOX_IP6_EXTERNAL_ADDRESS: "{{ .IP6_EXTERNAL_ADDRESS }}"
        BLACKBOX_IP4_EXTERNAL_DOMAIN: "{{ .IP4_EXTERNAL_DOMAIN }}"
        BLACKBOX_IP6_EXTERNAL_DOMAIN: "{{ .IP6_EXTERNAL_DOMAIN }}"
  dataFrom:
    - extract:
        key: blackbox
