---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: quic-check
spec:
  module: quic
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://${BLACKBOX_IP4_EXTERNAL_ADDRESS}:8443
        - https://[${BLACKBOX_IP6_EXTERNAL_ADDRESS}]:8443
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ip4-check
spec:
  module: http4
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://${BLACKBOX_IP4_EXTERNAL_ADDRESS}:8443
        - https://${BLACKBOX_IP4_EXTERNAL_DOMAIN}
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ip6-check
spec:
  module: http6
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://[${BLACKBOX_IP6_EXTERNAL_ADDRESS}]:8443
        - https://${BLACKBOX_IP6_EXTERNAL_DOMAIN}
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs
spec:
  module: tcp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 172.16.69.17:2049
