---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: dns-a
spec:
  module: dns_a
  interval: 90s
  scrapeTimeout: 5s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: dns-aaaa
spec:
  module: dns_aaaa
  interval: 90s
  scrapeTimeout: 5s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: dns-caa
spec:
  module: dns_caa
  interval: 90s
  scrapeTimeout: 5s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: dns-soa
spec:
  module: dns_soa
  interval: 90s
  scrapeTimeout: 5s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: dns-txt
spec:
  module: dns_txt
  interval: 90s
  scrapeTimeout: 5s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: quic-check
spec:
  module: quic
  scrapeTimeout: 5s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://${BLACKBOX_IP4_EXTERNAL_ADDRESS}:8443
        - https://[${BLACKBOX_IP6_EXTERNAL_ADDRESS}]:8443
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ip4-check
spec:
  module: http4
  scrapeTimeout: 5s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://${BLACKBOX_IP4_EXTERNAL_ADDRESS}:8443
        - https://${BLACKBOX_IP4_EXTERNAL_DOMAIN}
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ip6-check
spec:
  module: http6
  scrapeTimeout: 5s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://[${BLACKBOX_IP6_EXTERNAL_ADDRESS}]:8443
        - https://${BLACKBOX_IP6_EXTERNAL_DOMAIN}
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nfs
spec:
  module: tcp
  scrapeTimeout: 5s
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - 172.16.69.17:2049
