---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: blackbox-exporter-dns
spec:
  jobName: blackbox-dns
  scrapeInterval: 90s
  scrapeTimeout: 5s
  staticConfigs:
    - targets:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
        - 2606:4700:4700::1001
        - 2606:4700:4700::1111
      labels:
        prober: dns
        module: dns_a
    - targets:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
        - 2606:4700:4700::1001
        - 2606:4700:4700::1111
      labels:
        prober: dns
        module: dns_aaaa
    - targets:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
        - 2606:4700:4700::1001
        - 2606:4700:4700::1111
      labels:
        prober: dns
        module: dns_caa
    - targets:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
        - 2606:4700:4700::1001
        - 2606:4700:4700::1111
      labels:
        prober: dns
        module: dns_soa
    - targets:
        - opnsense-ipv4-primary/172.16.69.1
        - cloudflare-ipv4-primary/1.1.1.1
        - cloudflare-ipv4-secondary/1.0.0.1
        - cloudflare-ipv6-primary/2606:4700:4700::1111
        - cloudflare-ipv6-secondary/2606:4700:4700::1001
      labels:
        prober: dns
        module: dns_txt
  metricsPath: /probe
  relabelings:
    - sourceLabels: [__address__]
      regex: "([^/]+)"
      targetLabel: instance
    - sourceLabels: [__address__]
      regex: "([^/]+)"
      targetLabel: __param_target
    - sourceLabels: [__address__]
      regex: "(.+)/(.+)"
      replacement: "${1}"
      targetLabel: instance
    - sourceLabels: [__address__]
      regex: "(.+)/(.+)"
      replacement: "${2}"
      targetLabel: __param_target
    - targetLabel: __address__
      action: replace
      replacement: blackbox-exporter.observability.svc.cluster.local:9115
    - sourceLabels: [module]
      action: replace
      targetLabel: __param_module
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: blackbox-exporter-http
spec:
  jobName: blackbox-http
  scrapeInterval: 15s
  scrapeTimeout: 5s
  staticConfigs:
    - targets:
        - https://${BLACKBOX_IP4_EXTERNAL_ADDRESS}:8443
        - https://[${BLACKBOX_IP6_EXTERNAL_ADDRESS}]:8443
      labels:
        prober: http
        module: quic
    - targets:
        - https://${BLACKBOX_IP4_EXTERNAL_ADDRESS}:8443
        - https://${BLACKBOX_IP4_EXTERNAL_DOMAIN}
      labels:
        prober: http
        module: http4
    - targets:
        - https://[${BLACKBOX_IP6_EXTERNAL_ADDRESS}]:8443
        - https://${BLACKBOX_IP6_EXTERNAL_DOMAIN}
      labels:
        prober: http
        module: http6
  metricsPath: /probe
  relabelings:
    - sourceLabels: [__address__]
      action: replace
      targetLabel: __param_target
    - targetLabel: __address__
      action: replace
      replacement: blackbox-exporter.observability.svc.cluster.local:9115
    - sourceLabels: [module]
      action: replace
      targetLabel: __param_module
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: blackbox-exporter-tcp
spec:
  jobName: blackbox-tcp
  scrapeInterval: 15s
  scrapeTimeout: 5s
  staticConfigs:
    - targets:
        - 172.16.69.17:2049
      labels:
        prober: tcp
        module: tcp
  metricsPath: /probe
  relabelings:
    - sourceLabels: [__address__]
      action: replace
      targetLabel: __param_target
    - targetLabel: __address__
      action: replace
      replacement: blackbox-exporter.observability.svc.cluster.local:9115
    - sourceLabels: [module]
      action: replace
      targetLabel: __param_module
