---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: dns-a-aaaa
spec:
  jobName: blackbox-dns
  scrapeInterval: 90s
  scrapeTimeout: 5s
  staticConfigs:
    - targets:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
        - 2606:4700:4700::1001
        - 2606:4700:4700::1111
      labels:
        prober: dns
        module: dns_a
    - targets:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
        - 2606:4700:4700::1001
        - 2606:4700:4700::1111
      labels:
        prober: dns
        module: dns_aaaa
    - targets:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
        - 2606:4700:4700::1001
        - 2606:4700:4700::1111
      labels:
        prober: dns
        module: dns_caa
    - targets:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
        - 2606:4700:4700::1001
        - 2606:4700:4700::1111
      labels:
        prober: dns
        module: dns_soa
    - targets:
        - 172.16.69.1
        - 1.0.0.1
        - 1.1.1.1
        - 2606:4700:4700::1001
        - 2606:4700:4700::1111
      labels:
        prober: dns
        module: dns_txt
  metricsPath: /probe
  relabelings:
    - sourceLabels: [__address__]
      action: replace
      targetLabel: __param_target
    - targetLabel: __address__
      action: replace
      replacement: blackbox-exporter.observability.svc.cluster.local:9115
    - sourceLabels: [module]
      action: replace
      targetLabel: __param_module
