apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:WMV802vl7xKQa9MoQK7GXdJO2VQTGi3oJMyrB0p20Z0Yuq6Hi0x9USR74SraC5Qkc4uHxKTw+zANsuo0rCPT7vkrtw90rU4bMb9fyHJQyrY494A0/roViY+/gMrv7m/ugk07y6HMpqxMH/3Xqvh667ul+mJpxlQZPdK+CPEBoqhaUKm5Pus0OSvtNWJpdw8BzqRyH3+kBpCpYq0ugxAcsgtbV+EJUWCuK+P+6kJdk6drkBTT,iv:hyquofokMQ3TgiJqyV34CaeaepDg12/pLJXMsSkt7/0=,tag:B1tbWs+9vCDv+20QgxM1ng==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SDNBMldGSE1ua2VxaXJF
        RFdwaXBRblpCZFEwQnFBVDlQNXlsUkdwUVgwCmRsMi9LVlN1NnVxZ055UnpKS044
        dmN6cndFbnN4TFU1MHVWZmFaeTJWdVUKLS0tIExVSXFGbmVCUkkzb0FmSGYyWkhi
        MFpMbnFzdlVONU9Wc3pFcjV4aDdLdFEKDncdb0Bv4RKDrTmZoFVINYlGduEkI/cO
        f3Au6UsMPZr1rhk+dhnnMd2HjN6CNx+Vp41DFeY0zL+ClGvC5NI6yw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T18:52:39Z"
  mac: ENC[AES256_GCM,data:GToTvdS8zsWll+SEgxuUomXwE/GNZ+VTiV6A4Aw0aI/+8PBycSYvm/BUPmYEZkJRbPzdY+ea+mL6+gs8CjYtWopACMrzxLpdql59KADYdwrH+JIGHgDv/PyY1L24ZsIwxyMiVjXO8Pb/okhnFV9CBdxicDkC8VYogeljFUfsNio=,iv:DE+yHlLhwgTDBH4ik7UW+MLvEW3CCQWAJzluSj956aU=,tag:yI/KNso02qF76/mvvGisQA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
