apiVersion: v1
kind: Secret
metadata:
  name: onepassword-credentials
  namespace: external-secrets
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:oMCx5uu7m5iBx8mN6aqq1uBpBVKlQfbo2Rf8ppEiHEbIPgbKfpIkOewMF1Phys7Y0HAh9BZ/5wFOYylWoqBAIVTdF8nARDs1DctHdYzatD3l642V8QCgUYc232AC2nYuk6TOUMoB7fyenNlJNb2+n1lGXEtFimbccDsAOigGRRYgoL6fjMrx2I2gPVBeGmE8z95b72ji7iHAtK9ujuD/Acj8lcqG4619qT21eNPjabqgfw7hh6B9aXjcQ3jFtoiaOKIVOJQG5EgG/Vvqe7/KIYt6lxofRFFwW07ZvxSvVKI2f+hyqwr4sc/6BU+MNvazwysj492M+FD6My+jq05m55aK7OiUcYn6xeYEj/v/6G6VE67EQrRD70KcG3hL458kZUZ5fS06jhgt7FIIXwbqPW1Ok96bBLJlhvPm5ORbOoOn+PK/bZtDNX7HK499enzUkUjlGz9ihhp8KJ2521tMbK+/eubBOB5hv494Pj/afn8kSmfYSF1Tu1Qjs5DLUw/HTLm2X+VJDohRYm+4Hg2rZgSyxl6KUGdDNIi+TxNZOGYdWTg0VbToI3jth7ybx2XwVQOwnL0SzLa80v2JY0RjihS+U8hM71bILNr4HzgX2Ndr4/GOXUrUbmA3BpcOnzq+TjngJVKfJ6mf3rKfnfRuOzvfsPGoVccyGLG9bIeXugP1yla2JB82NMOkpalW5fwirZLofLVPyZR85EXUokx9rw85owbm/OTPdHdvCk49rzUqLw3RZktP9nFFXSTokkKtyHTnb/uGfxWg90ONxsY3ukldlkgNoWh+96jJKVUkL+cw6rd8OMQC4f9qJwbyu5EI1+SEdr+tMlFk/Xsq1ajM7Vm02i8tqyFr8rmvUdLMaaOr6xLy8cJTDmTNWgdBPwA/2GuDowhevVcePGk9kA2VJ7dtrKxuOzX2ah/MZFybiYnYL+2+AbZNYgk8L7J2TLfkrwCEmsiS6FlAuXMRyfBion7lJl/V68WEsOOL6v5vs9arxulKQ2Jq7WdtoiZjZ15G+/CDoCkfsUjhpk01JFF1cwc9stIGuiYP53BByqG0B9CKv6LFrVf++riTRJq2oNgiQMukleedShMWOYI/cmkZoUot+0eBZZqTYjRXBRa+62xXgpey3wUovd5PJZ29kJs/vRR9EYj07xhBO1QLli38MQTCFW3mtL8osD3G3IMZtbjDe5Fi3BqKDi0jVQQIoqAmSqp/uMs6Dwuhf7HbnmJOSBKpVq6kR8yuD5VYgQyk0d4yghVYoFuINsDV3G5AQawXBM61VsDkItscjRTojjIR8U7RTSmHDSZ4H5NzQnO2z2EwDxFlwbD9PEUrsL0Exzt3O1P6/tEUC9URFrfvy1lyB80fTsfPk7zm0WAwppDgNBzK/rHfLierEyLSEsy3Tv/HO+gLks0z7aP7OoorU5GIvxnI9PdPf11C0p1j9OsWBsIpTRp2Ctr4eWWZUmqUMIJUu4eKJ4b/FA8NAtARj4KTSduM8OILdDRmbqjFmSoPHPg4Z6bp5L9ksDgTo9AWhAeSvoc8l1UcjubcLNrS/vqriI/yoeydi5MtCcQ4Oin5WwpeQKKXz5gEqdr57h9dXrMRt52qtWGcz86ObJzydIJ/4hobvl/xm37lVaZc+hoUNly12TvmkaFl0lZDedUR0XaBBh72grfznDUZvJED/F0WQ6hupW6NkkBp+8LdA/mE5SBAdHekEfboVqq7LyoE3YjpUhdll8wDQ0o4qJigbehb0N636haOP9+UN9elmV29kKUQPj6lLBnQ1xl9faEnMr1XCqxEZU3FApjue2uy1a0XTYk5Zw/ECwUyyDhGJIiX6jU8vnLz2/HkmKhQDbvMhWjZ5QTH2HOJYkVSzUzlvTMc8D7e5qYW2YfMGOjHN8HkaRTUFyrlRmYLm1ir764AwHPMr1nKl3kKYLzyFD+a,iv:LA2bUdvjjcTzsfj+86+s8fOKuT9sAuqj/of7iwU6P7Q=,tag:RrON3cLHpi0rwDPXL2vXOw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RkFkNjl0NktsSkFJUWdR
        cndyeVNPRG1ocG1IWGd6V24rUllDVU4ydDNnCnRrcnd4eVlEbjc0Yjh4K0VIcUtl
        Rktqa3lUUVdVc3d6b2N5NFVCVk4rZDQKLS0tIC9TV0FDZHV4cEVEQzRqdmF1aWN6
        VzUrWlRVYW9lNWVRRlQ4ZStDSVJnMTQKUzbVDL+CKCxQ1PYDpl2hAaLMNT3GrCQ3
        TiSkt8yWAYeemORkqlWF7bg1OBS3Z3NlnIm4H08TOBk9Z3Z2qDrilg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T16:11:05Z"
  mac: ENC[AES256_GCM,data:1CxPAS9/YrLl75145OSuWflfeozymR/nNfqUt6ltZogZbdkzEbKYOgd00udMb9eZ05FaqcqPB/qs0KyrW2ZDfCC9Y2VGZ9MRYvS0Unf5Pj5KHM2TMeAIUT4Z71aNyM55+rqAn30vgPlr7VAh0pZPe30EW7sxlwzGhF9/r9jpwjY=,iv:w9SEt7p5FWQ1H7Cr0GyO+gXloqPA4SnF8Ep3psHwgxI=,tag:SIaKB7KAuTQc+X/ea+UBDw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: external-secrets
stringData:
  token: ENC[AES256_GCM,data:zfAIL4qYxQ5jZ0cilGJdEoQ8DWTx/iUXlzHCBgLUUPQfIn6fpC9mJnsUJqvuf2RyfA13n1mil/FLP3U5/ohU2AQvvP00HBfUsoYZOb8pw6D5uQ8RcO0nfESojTHiA/3i1hCS/wJejJobedr8VsQXVHZ+fAtEnd8GmRLcAyt3vLSV77v3Z9NH3BScWbx739FPaOnh3nW1VVyM93LqDWVpXKKrhE3Gs53qXxc7HRaSy1JVCB3Kxfk9AXiLfUqyyO77JgKtTZunGugkEpgpMBqJ3ojYyad6xU4gA3ZTfkt+De+gTGbCtUyXojRb6jVWAqWVGxUika+p93PU6I2943Jb/zLgZvr1hfu0r9anC8izwhAG9SpwA94SF6nLkRytx7EE5YaDmDQ7Qgs3gTjDawigCszCXY0BLuPPnOu4EQqZkhtPKS52eHlbWWUiiUq5+cX3h3G9Sli5OVngX/Aa9Z9D/fi5LszBeyym2eWwCy4qDOq+Gn+d5ZXJ6NVz3e8JM4o5ZDHbs+P1m1PVm4JXIumqN1eTOClrUkRl8bUPQfmsf/8OUSFTx9L3Hw4/KQw2RkqE1axE+4EQ9rllu2giL8yuEJviHiUGJEZsSfmxYAv9MB1/2UCE3RawsgrEvgDWB962WOEVwoZivvD2AtDHG3jVTq1YYnMOIE6ISbhZS4zNbDXCbnX73CeOQYOE9n9BYtlhCsR+RIH5Ln3/wg11HqbglonYdbotcrXT3QzRJKhLK7S3PKnFyE7ENyhVoGV7KXB21/sZaGNcpLX4ap8RGVMOlyGbNzNs6krxCtI6DQM0AzDrhnjocKc/6hMwWq4hpnUTFCTG3pk26Hq4hRIoXVnpKEq8pPpiRii67lvq46ZdS98qpfdiBJQiE/E=,iv:ep4us7uXJkbRCOfFxWBYll/r/rhLdZ8t8yaJNkVvxs0=,tag:Qh/5//Q/QodT/B3cOeszVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RkFkNjl0NktsSkFJUWdR
        cndyeVNPRG1ocG1IWGd6V24rUllDVU4ydDNnCnRrcnd4eVlEbjc0Yjh4K0VIcUtl
        Rktqa3lUUVdVc3d6b2N5NFVCVk4rZDQKLS0tIC9TV0FDZHV4cEVEQzRqdmF1aWN6
        VzUrWlRVYW9lNWVRRlQ4ZStDSVJnMTQKUzbVDL+CKCxQ1PYDpl2hAaLMNT3GrCQ3
        TiSkt8yWAYeemORkqlWF7bg1OBS3Z3NlnIm4H08TOBk9Z3Z2qDrilg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T16:11:05Z"
  mac: ENC[AES256_GCM,data:1CxPAS9/YrLl75145OSuWflfeozymR/nNfqUt6ltZogZbdkzEbKYOgd00udMb9eZ05FaqcqPB/qs0KyrW2ZDfCC9Y2VGZ9MRYvS0Unf5Pj5KHM2TMeAIUT4Z71aNyM55+rqAn30vgPlr7VAh0pZPe30EW7sxlwzGhF9/r9jpwjY=,iv:w9SEt7p5FWQ1H7Cr0GyO+gXloqPA4SnF8Ep3psHwgxI=,tag:SIaKB7KAuTQc+X/ea+UBDw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
