apiVersion: v1
kind: Secret
metadata:
  name: onepassword-credentials
  namespace: external-secrets
data:
  1password-credentials.json: ENC[AES256_GCM,data:0smNUlka6xoekMqo/XJZjqPlfmSU5dZOZVQqpJ6MkRReOkynN7USmPG+dKmwrmXfQ5+XVG0ZrgjG7/0Xwc4ciOSVn5lHtob1imGMHFpCRZSUDE1qevBx2SC8zbTqOIAZEJa8XZL4NsZAuLA8a6u3XzWA8haE4iO4GCAQL+bnpvNJ9roZ61qbhzXzdw8c54UarHaxQG+fiMwn0AoeTUVtvHIZ2YY2mlj6eT62u8FYKsErWi8/0mbAKMvfzCI404kVKVOJNkR2CfPeBiKfrKolRhzI4oi4Cf55YqN9xH3vCz+R/mf+nRzHbP34uBS5owiEirD0x9VbhsxMEh1eA2txhpE5yw1lA5MtvuZckuniI4JjHqJy2nLiKKT5q9bAmi2F+77MiAIM53V+kjcPkqko88ZP4f8OpnwfkH/X82b/hs95V2WXh6WSShfAZqalrlNjSXpNUCx9tUujfZTmyx8tf417FGUuEpcK4b6gyVF250fqcf3OqWevlK/zB47bMRtFEaysFfZtPDjFe/ApsZ01R9ijUCp8+/MsUpQHmvgzn4fTHa9/k9odBZFSAAD8hhM6u2Kbtz93+PfgMibikX7KhcJYEagqsmlnEZoglUVesJKtP68gRx+tFdG/fJvQ9fVnUSVT9dK8c0/sgXtWbvI9njUJ+/YCpdvSQ3zdwOyxX5gBcSZrApQVBZjvsCz24KLsQbobwPYZObcmHoSSE2pax19g88zzNIF5rzl6i5AXpopplKdpLm7+L3Tzz7lq3Y3UMG4G9t++tifN0uaL5hI3ZAB8iwTIAyXS6mHVCfmH5ti1JGRa1KPWKxOptdKozBZ0qQ4c7MNHMUzo3IYr3D+KRsuekmL1fuqnNEQkZe4ai1ZQkd9pLyZL9+4jONeWyXV1NsQFQRtyGdIH8Nu69RYjiaUB/RaYp49Z4O7SKYWIIfDbQwACj1AxGwUw5TA8OX7Jcs5zmOur0v8WpzUJp/UnBur7YNdw5fk1F0DaEvYcBpHc0lPD7P5OAqZrHxzFiaxOK56BE2mgs+eZSBi1HVLMrLi/wSgnPhvxlWIp6+Q2WdlwzdL/4xolKnzJoOAh4ScKKFzTwf+armhgj2xP8fa4mcacro1cMOpTG1Y0bgqmYajGdWYYdkQXYajjnZ179pJKPp4KGNeBZz0ccmOM8kvxbVuNS4XrQh2S3Vh8eelZnFXLvOcCdlHlNdEyV8nzdxFBXHjdqcQiPPs5U0eecjaQ1jV21l+CAv0jZJnMx1pUDYFFhGNl8Xta6UwcUf53oDtgGhQIePMGMp2f/zdfbaKEFXvEOmzD99o9mvbMYgPfXUOJ85Yq3QWWxh336o/2LFD55BjCujaflw2AkmAealo/cZ+HLj3WVNx8iFvx7yl893PEfNo/bu2pOEjgSQ9GJIiLiWxcoZbWXllEx8aIuZMuNkQqcOdOMvlrPgwiyfdaU0kb06Kiu2p/c5VfFNCTdD7TPELkR2ZDCWR3kpRQGx2MvjVPeqJkcS5KeBN9tXzcrDf6mIZBiv1BbOqoIVYAc3GrYJxi20o4tGWbBUxq8ZitcGLzbkLlRKWAqOdNRm6ScwWzymgwiQ1nb9bXa5yw6HVRuxnsTgMkit26xns45Un6p+HFImMz8R1icGe2ngpJ3O0AlEkQm4R6Um49FbSD//3zWTcuLT4A0id2U4Rg0yU3kevO497D7QHCcyKRnYnPlSgcZQO5MPYx8IbHP0dlxvCRrz6MfMT0SmEJjj6T8svSq7aiXuNO3ANBLV5p5VeDaoaYDm9sRYsu375NZM7ICeAzdmpnsjCF4c3SFulVZvB9rOTW1CGXc2ewNhWALgvh+UMil/7PhcFKeYrEwJakfJz/TpHSQE0TUj5DpRSiuYR2onEbDho7w+3JBOUe/zZ3O8IGfceETJATqXyiz/7O9LZR66iLJGgv0T5FwJKJ,iv:we9KzR3pof/UQ7dzdQGexeM4GsICW1nodS7keaMUmYI=,tag:W/+cUzs8canYPOF6l5kI5w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNUVJZ2VZRklRb2NXeWw2
        d1BQSXRRRUU1eGZNcmpFVXhwdm5HVm10bEJrCmh2ekZXMjI0UTJnQ0xOY1UxeHRi
        MDdFN0ZzSXNiS0l6SVFDcWRMOVdJRmMKLS0tIDVqWmdnMHoxS2lCUmIxcktwdVlH
        M3pTR3RtMElJWnR4UWtTQ0pPN3hDQlEKCu0jIFNFI9v8EqPRbZy9+7K6QEM7Efev
        c/JUWBxfTpHyeAyb5liX2kYsv2M2xe232lnUSzrAUHyO64gjpoAhSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T10:58:36Z"
  mac: ENC[AES256_GCM,data:8wHhCi5ckjLwYwPPuUIIRoEUw+9vvRStnKi0XP+cjEcjGLqwKC+wcPzEGQ1BQsEctSRDAKZX+D85Vf/WoFvYttOLmUg1zaCUg+B0e32b4ftUqj2IFnCtpC1vE7MJ5ATv7GteCqUC8ELZ2KNBbZeQDD2h+DigRopd93LLCvXiqqM=,iv:ECOz5bI1OTl0jFEU9RhHi/LCd9gMQqACa0qiLMAMZe4=,tag:tvjeRKkbMVcCa7u3trThYg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: external-secrets
stringData:
  token: ENC[AES256_GCM,data:XbO0Xl/6mu6X9n8eXn9MhoQKQJ7MormvFgbvcCWqExSIN5M+v99cqJXdg9UZWALC7hxT0YWLyy7QML3p4q4oeT1Kppw6TsptJxlSu0hYFH5N+qgsTVlcT3MvnqEFGwTxmJPnbU8Vd6695WxGvr1MPO7dO9KZvkcu6ahk37sqPdUOB0099M4dLmJL8TpMRteO78aaDahO7p8e2WnWweuyB6AHfI0JjrUkxfze/r0pUDZ3RG7ZNhWSd6h3ukd3+iweXSB6ubt20G/h2eVO2lQOSr7Ie4Ws7vKCmhK02iJo06WzTuEWq4nxWgaQapRcZpll9AN2tsXPCB8LSHEYStFOYQad0bFGBj3NaTpCeawBJzwm64OD3SFZ5dP2UetWasStgTuFrdcg6SB1sz2fxKemoCSyId9R5fq5by1m4rBRGfET9Rm/32mBdn1c/3tK57J1H4LHTE4BsM1kbpiQxmt8Li2SqG6UQXH2HRtgP7GaImFJsXmozFySTii7fjabfw4vcds/1Z5BL22dg50o1Lh2XGWdcJ9ebOZ6HM1szFOim7CItR6JO6RJ7HUg4UprHF0d/9nIPYKWXxhj52NkAiGmWBHBDdWHBJn4IsKSc+xRCYN2ASrUW51AlNuyywqyR6gl1dvKxphrdxJ3ps6pEspJFZDICMUAcIFmVKz8Gdkp9fsEQdDuN5eKnIjml8nJu4VRdfCj9NFak4InvVf5xjCh8UlAmLuoHijbbRlIWJXVxQecDfwiDl+QxDaD/m2OmB42V15HJUEpOd0S9c/tiEVMa/82RWop3DICfVEhBghNdJf9wh5uvMHS1rwnr6o1kDnn4Ofw8T2rvGW8mmDC7N81JsaZfLvxxoSUAdO00OdS50tHBoI3gt4QIGg=,iv:Ox58KRlJgotXAZ/aTd7eKHI/+ml62T3tijjEeVa+u4g=,tag:4k+ubnmmDfqXe7PFIeKC6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNUVJZ2VZRklRb2NXeWw2
        d1BQSXRRRUU1eGZNcmpFVXhwdm5HVm10bEJrCmh2ekZXMjI0UTJnQ0xOY1UxeHRi
        MDdFN0ZzSXNiS0l6SVFDcWRMOVdJRmMKLS0tIDVqWmdnMHoxS2lCUmIxcktwdVlH
        M3pTR3RtMElJWnR4UWtTQ0pPN3hDQlEKCu0jIFNFI9v8EqPRbZy9+7K6QEM7Efev
        c/JUWBxfTpHyeAyb5liX2kYsv2M2xe232lnUSzrAUHyO64gjpoAhSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T10:58:36Z"
  mac: ENC[AES256_GCM,data:8wHhCi5ckjLwYwPPuUIIRoEUw+9vvRStnKi0XP+cjEcjGLqwKC+wcPzEGQ1BQsEctSRDAKZX+D85Vf/WoFvYttOLmUg1zaCUg+B0e32b4ftUqj2IFnCtpC1vE7MJ5ATv7GteCqUC8ELZ2KNBbZeQDD2h+DigRopd93LLCvXiqqM=,iv:ECOz5bI1OTl0jFEU9RhHi/LCd9gMQqACa0qiLMAMZe4=,tag:tvjeRKkbMVcCa7u3trThYg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
