apiVersion: v1
kind: Secret
metadata:
  name: onepassword-credentials
  namespace: external-secrets
data:
  1password-credentials.json: ENC[AES256_GCM,data:1UTAjfYZ5vN5Z6axtaXhQaERcEJ0rScSr497MJstpKSUtYARMK7neM8prqUQ/ZxOBTFS1HsS9wZxLhv4z39FQIZWI4g7j7N/M3Sjm2itrupsxuupQYvS2nWxF2EiqHO9u02lXNmm6SWi0Z2bty37vMz4CW/Ogf2Oy+6Z9OMyIHvWNrRTv1W/g6GDjc01p1g6cYESNEbJLABT6vz/9sGyZm7uhCj6YiF4jh2l7+N3NBsHKNJqd480eBtkjJypkLDKtHYco7VD7c1lxkHO+0TC6Pqb6yJPaFI8DNd2j8KU5EsxOlGQAjG8eQ6mhuG1K2tFl/T8bS/jQnmNblUw10WO99/q0nZQuVsCL7q2OcTM8S3xVOLe1BzYOAulcRNewGt0x+jhzZyeP54eSgC7mupZPiM0Ljbb5RhZmg3J6xioSyeq2RA2q6ugapzcIP2ywRBIfkOfn95NSPEyFQEJdU00pbYi/7i0VqmNAwGT4HGPn0Zi8hA5yi/E8Ps7VGbeGk5WMxNwEX0niMcLJF8OO3nOWWtl4WHKMhT5+DXiRWHq9+1KXXvPc/2lhuwxnPM3Zgqe1UWwKkl9j156A4THjFIDzAKvrOzKzqhqNvL2kcLrkQ/IJgtN76v7Fx6qpUsAQAJZj2Daq6m1usLTgBwvRzi2xl8CgxFt2c/oWmDIH46VE1rlaJYCx7t82PkFbLh/t8ZVlE4N5TheUCUFMgXbLKQAzALKNo3117aLpsmNmfAUvLqYWTJIYaPiSRvfimocQ6N9VMCicn/3vUquj4Az4kscTpXPC/UVVC5KkaMesDOPcimAJX5k8qgsqvmMxog5CBMpQB3vED3zvhUdIlpAZdkId0nyEpNdl90zHKL/3Ked/6o9Gv+tKQ1LCaCnjjTkbi7HZx2qDhXJZUM2XTI+3dSxNcTa9K7ATmAsL8VDqO1Dk8uEwhIqjARo5plvIWhM/6T+cjvTLWrTp34Qsk80nTDtdH0V4iFOM1Ie11mUl4AR+oBANvJi0R1+oPTjEpNPCzEBt6SrWx2Yo6RhvW/H0UPAhYOyuhlfaj0bhFOsOfJio302T5OZqQHLlh/H9RvG5y4YNdPlXoLE/LOvs+6ggmrV6/jvxgom+Oz0B+HZvZhIpR5E/qvLOigRIh51ow67FgTt7DJGWUJUST9a2o3Z3+7moYgzmIpr33UvcU99Wl8sQExxQu4+pwSZw1mVmt/Lh+760wI/Oxcfo9mCdxs1HOxa8xkvYhu8lhjnPYpNhXKUH8vcsaRHNF0Hmbf0lq3jVBEiO44XyNK6YQ0lCuUbV8FWVhMnCyGVidqEmUMVprE1bAF44pxCXvJ7vSBDeWODG550L9Q1uE8Oc9crscS2j/Lhsfi3EG4Ea7ys20VpJZA0xLmR8JrrDC+PUN+SYPN5zxBi9mmxbRwAGUhfSYhV0oM3BGGJ7WYbrDY4l0s2OhAMqsakwbWEXwDen22n1FOTW62lqk12O315K8GJ1UnzOu6uD+NP0Tn/mPtZDpZ13mw4zrrujLn0uIzhMv9qp/0py5+GgcQMPkId6L6+DX5xAxy7qW1gpwjBY1RltYpfbOaKKRaoeB2V/UAZL0PWBQrJxr+BoWp3raILjkMuPR2KPYiRC9fNDuO6cZbLWZHrzfR6KZL6HwWoRXS6EQrwjXf10X1o5Rn2p4bqL+2UbqpouV8pG5Ax9YiBbrjFJe6DRSRQvbf7cqc6iqXjc9XE00kTwq4ErlSkpe1WjNmGgKkf3fx1RtT6TBSqj5cDqAaOUunz1z87ibAyv+7vCOGl3hl3O9XXd4lWQPbefIKejkLwOgEG1O4WcLIUBfpLeDQJbXV8jhdtVLj8mXulY4FdVokdky9erTFxbHxc9LkmvEfBiIduHAwMJMn60s1zHuBkseDW1Gi90nAAn19iaVI2swTiOCvjILSR9f+PEE1H8r3Z,iv:owI/fXiW3pyZQYeiIwvO6nO4j3NDTpnpxuuh9fIdJfc=,tag:/8X/KXo9FFJNS5WVorqylQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYjhYKzZBdEhJVjZxSElu
        TzNpeCtjQ2ZUdXM2UDY0Y2pTT2FRYW12MDM0ClVRaTdIUDExa0ZXdjdkSTduOHpD
        cndIMXg5eFF0eVIwQWpJVTNjNG1xUjAKLS0tIEpmUWN4MUdWM2JTTWRjUHB4RkRY
        TG84ZGVWRTBwMzdZTVJMa09mblg5OUEKJ27vKEXx6DPPPN4k6kWplk+c2iBV56wt
        QW9jXtkgFkG10DD6kNL1gfaQvK1PvbrsPtrXe/HFKXOGL5VdpemW7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T16:19:13Z"
  mac: ENC[AES256_GCM,data:OHPD8grxx0bhrf1mgtLg7rJkCDPe9o72Uf7rgjOT3e3nrV3Tq9Xx6ecFOlPc0SKJvPsOW0yWnwukDM6Xgnjbscfl8a6AO693IGSmEnTH08A1syiIZ9JBHacsRp+sy/HbhIqrmiSMHHqEBingC9hxn/txEmHuVvGY4Zk26Q4VQrQ=,iv:boo9/G+Ky+M3l97koqplZfpVdl33JXLsnuqo2aRxnM0=,tag:qgumPptI/mJBbdUBWiDqnw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: external-secrets
stringData:
  token: ENC[AES256_GCM,data:U+9X/1O8v2XtJpgXSb4erv1n99zCOgZva9TNjAk/U1XpB7/bIe6DlQ4Wm9LOxFzIQdF9Gr/LUxDZ/s8Nq/wao86gjlHaioa1bRdpwZ7oM9HXIrAhw92W/Gule7mcM8SlGBHtpNiGlOCsvWEsf8/jdx8H1VvqouJN6qEzrauCfhVvxpxFv5Y7R5yHuZcD/15XshjGuCuJ58vfUYuudkRK6QYjNxaa2h8guQ8N6j/Yr04vre8HWhwfK8GsUnG9vtPPk/AumcqRnVnPcMy8ElryFGL9rK2qjQ04jQELBVHp29qrad+1q6kgb09V2GtRIqtsZ8e13Ft84yEEAm8RVV81n0R7cMnUBRCR/DsDbxXOrVGPu2+Kh8xQ1v/YHGhYprTasaizKN6c37id8CXasZ1kh8Z4T1N3tn3sPUPda797MTnjRzUK2v58kDq7aTQnJPYtcw5lkwSyMa++dlA2r6Yg1XoCvMjTKZlK/T4xy/llnYuSvzsolULBml6XhNGVY+buEEJbxrCuJg2rf2TKvN2Hx6kECUUv/o7ZZO3cs/2s91Ry3olc+N9pm78ima3k3x23DqC0/USy015HNhol2r1KOGTr4S2TjJ2ZH6tZL3G8RZru5Cf4Cl2QrvltpDZ/5p0nfXbFj42TV8ZUtHMPpInpTZK9sFebRMdMfadk8E5FdQduEbXLyydt99l4bx4IbBevdPVDQ2zJ4n14C1xSgWeHwZ0YvLbh16/1P45VJ28J0Cz7TTcX8HKJR63NnQZaTMWghl/YaenKpCtGEHvk/VFQn5CpvTbhXy+kSfL/LCrtqcjc+vyl4u9DPyyqUDiWSeMVmbeZSuzeqV3ozs6OgSUda5hpFAoxfRovM3exGGiQthbfg3rgUGDMwEA=,iv:HWc/SKLly/4X0s7FRULNS5OHEl/1yqgMm2FvkCHCk7Y=,tag:nM7X3Fq9NlrYhe373qBYDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYjhYKzZBdEhJVjZxSElu
        TzNpeCtjQ2ZUdXM2UDY0Y2pTT2FRYW12MDM0ClVRaTdIUDExa0ZXdjdkSTduOHpD
        cndIMXg5eFF0eVIwQWpJVTNjNG1xUjAKLS0tIEpmUWN4MUdWM2JTTWRjUHB4RkRY
        TG84ZGVWRTBwMzdZTVJMa09mblg5OUEKJ27vKEXx6DPPPN4k6kWplk+c2iBV56wt
        QW9jXtkgFkG10DD6kNL1gfaQvK1PvbrsPtrXe/HFKXOGL5VdpemW7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T16:19:13Z"
  mac: ENC[AES256_GCM,data:OHPD8grxx0bhrf1mgtLg7rJkCDPe9o72Uf7rgjOT3e3nrV3Tq9Xx6ecFOlPc0SKJvPsOW0yWnwukDM6Xgnjbscfl8a6AO693IGSmEnTH08A1syiIZ9JBHacsRp+sy/HbhIqrmiSMHHqEBingC9hxn/txEmHuVvGY4Zk26Q4VQrQ=,iv:boo9/G+Ky+M3l97koqplZfpVdl33JXLsnuqo2aRxnM0=,tag:qgumPptI/mJBbdUBWiDqnw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
