---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
components:
  - ../../components/sops
  - ../../components/kopiur/secret
resources:
  - ./limitrange.yaml
  - ./namespace.yaml
  - ./kaniop/ks.yaml
  - ./trivy-operator/ks.yaml
