---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: daemonset
  resources:
    limits:
      memory: 512Mi
      cpu: 1000m
    requests:
      cpu: 25m
  volumes:
    - name: hostfs
      hostPath:
        path: /
  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
      readOnly: true
      mountPropagation: HostToContainer
  config:
    receivers:
      hostmetrics:
        collection_interval: 10s
        root_path: /hostfs
        scrapers:
          cpu: {}
          memory: {}
          disk: {}
          filesystem: {}
          load: {}
          network: {}
      otlp:
        protocols:
          grpc:
            endpoint: "[::]:4317"
          http:
            endpoint: "[::]:4318"
    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 70
        spike_limit_percentage: 25
      batch: {}
    exporters:
      otlp_http/prometheus:
        endpoint: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/api/v1/otlp
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
            - hostmetrics
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlp_http/prometheus
