---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: daemonset
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.161.0
  # this enables the servicemonitor for the daemonset
  observability:
    metrics:
      enableMetrics: true
  resources:
    limits:
      memory: 512Mi
      cpu: 1000m
    requests:
      cpu: 25m
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "host.name=$(K8S_NODE_NAME)"
  volumes:
    - name: proc
      hostPath:
        path: /proc
    - name: root
      hostPath:
        path: /
    - name: sys
      hostPath:
        path: /sys
  volumeMounts:
    - name: proc
      mountPath: /host/proc
      readOnly: true
    - name: root
      mountPath: /host/root
      readOnly: true
    - name: sys
      mountPath: /host/sys
      readOnly: true
  config:
    receivers:
      host_metrics:
        collection_interval: 10s
        root_path: /host
        scrapers:
          cpu: {}
          memory: {}
          disk: {}
          #          filesystem: {}
          load: {}
          network: {}
      tcp_log/talos:
        listen_address: "[::]:5140"
      otlp:
        protocols:
          grpc:
            endpoint: "[::]:4317"
          http:
            endpoint: "[::]:4318"
    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 70
        spike_limit_percentage: 25
      resource_detection/env:
        detectors: [env]
        timeout: 2s
      transform/hostmetrics:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["instance"], resource.attributes["host.name"])
      transform/talos:
        error_mode: ignore
        log_statements:
          - context: log
            statements:
              - merge_maps(cache, ParseJSON(body), "upsert")
              - set(body, cache["msg"])
              - set(attributes["talos.level"], cache["talos-level"])
              - set(attributes["talos.service"], cache["talos-service"])
              - set(attributes["talos.time"], cache["talos-time"])
      batch: {}
    exporters:
      otlp_http/prometheus:
        endpoint: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/api/v1/otlp
        tls:
          insecure: true
      otlp_http/victorialogs:
        endpoint: http://victoria-logs-server.observability.svc.cluster.local:9428/insert/opentelemetry/logs
        tls:
          insecure: true
    service:
      # this is ignored in the current otel operator version and overwritten
      # when it's fixed, I can switch to periodic
      #            - periodic:
      #                interval: 10s
      #                exporter:
      #                  otlp_http:
      #                    endpoint: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/api/v1/otlp
      pipelines:
        logs/talos_machine:
          receivers:
            - tcp_log/talos
          processors:
            - memory_limiter
            - transform/talos
            - batch
          exporters:
            - otlp_http/victorialogs
        metrics/host:
          receivers:
            - host_metrics
          processors:
            - memory_limiter
            - resource_detection/env
            - transform/hostmetrics
            - batch
          exporters:
            - otlp_http/prometheus
        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlp_http/prometheus
