---
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: victoria-logs-server
  namespace: observability
  annotations:
    external-dns.kubernetes.io/hostname: victoria-logs.${SECRET_DOMAIN}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: victoria-logs
    app.kubernetes.io/name: victoria-logs-single
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: syslog-udp
  rules:
    - backendRefs:
        - name: victoria-logs-server
          port: 514
