---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-cloudflare-issuer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cert-manager-cloudflare-issuer-secrets
    template:
      data:
        CLOUDFLARE_DNS_API_TOKEN: "{{ .api-token }}"
  dataFrom:
    - extract:
        key: cloudflare
