apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:AzQZ9fz8aKfbPRPOQ1YCGSiMsuPbJPx5uVXNk1j6ZQLycxh71FGWh25MRgx5bJeWIrUwbS0=,iv:WbODNymaciCZKCULwQ+BwaaIFjR7f/tfSJJZwGk1xlY=,tag:cQR/sQPGVk9zk/0VMpr88Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRDJEbGswcTdjY285NzVL
        NllrTjA1enVPRklXWk83Q3VwM2ZwVTlCTVZ3CnRGU0JMU3lLMUxqVTQ1bnBBdm9l
        N2FTM3ZqV2R5dWdoN2wveEJabC9GVFEKLS0tIFAxL2RDeTIvVE9JZXl2TEdvOGtM
        YW5hZEhUQ2FicXJyMC92WVQ3R2tUS1UKYS5iPRLc1RxN4+vdbZSXhiWvZs6CaF0r
        axpuUApjcwEVJ5ASWzSESN6S55E2mbVkqO7yLVO+atM9wT2ZwwVtBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T18:52:39Z"
  mac: ENC[AES256_GCM,data:G8aXRxEcJeZQpdXC8ipriCvbvB7BUZTVEx49OzS0+XNq5nfX57Fq0ieH/5e+hwRD+ZCvF4t5hQ2cPi8eKFtxbVCcDYoWtDbLZmoYiPpL+Snb2OwYdXSD0BZrw81qrP3FNY73NHHQi2nnJnblm0NN6p6eZBZqOoNc++ZKTKlzWN0=,iv:XrDygOd9rDMIwHDv4uL4WUgu+jGQ6rihOakXp3O0GeU=,tag:5Iad2CnrZncaNgXZfGGzdw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
