---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kaniop
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    logging:
      format: json
      level: info
    webhook:
      logging:
        format: json
        level: info
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      dashboards:
        enabled: true
