---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-collector
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs-collector
  interval: 1h
  values:
    fullnameOverride: victoria-logs-collector
    podMonitor:
      enabled: true
    remoteWrite:
      - url: http://victoria-logs-server.observability.svc.cluster.local:9428
        maxDiskUsagePerURL: 10GB
    streamFields:
      - kubernetes.container_name
      - kubernetes.pod_name
      - kubernetes.pod_namespace
      - kubernetes.pod_labels.app.kubernetes.io/name
    extraArgs:
      "kubernetesCollector.decolorizeFields": _msg
