---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator
  interval: 1h
  values:
    resources:
      limits:
        cpu: 2000m
        memory: 512Mi
      requests:
        cpu: 30m
        memory: 512Mi
    serviceMonitor:
      create: true
    web:
      networkPolicy:
        create: false
      httpRoute:
        enabled: true
        annotations:
          - external-dns.alpha.kubernetes.io/internal=true
        hostnames: ["flux-operator.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
