---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    template:
      data:
        OPNSENSE_API_SECRET: "{{ .API_SECRET }}"
        OPNSENSE_API_KEY: "{{ .API_KEY }}"
        OPNSENSE_HOST: "{{ .HOST }}"
  dataFrom:
    - extract:
        key: opnsense
