---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
    - secretKey: opnsense_host
      remoteRef:
        # 1password-entry-name
        key: "opnsense-secrets"
        # 1password-field
        property: opnsense_host
    - secretKey: opnsense_api_key
      remoteRef:
        # 1password-entry-name
        key: "opnsense-secrets"
        # 1password-field
        property: opnsense_api_key
    - secretKey: opnsense_api_token
      remoteRef:
        # 1password-entry-name
        key: "opnsense-secrets"
        # 1password-field
        property: opnsense_api_token
