---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opnsense-dns
spec:
  chartRef:
    kind: OCIRepository
    name: opnsense-dns
  interval: 15m
  values:
    fullnameOverride: *app
    domainFilters: ["${SECRET_DOMAIN}"]
    extraArgs:
      - --gateway-name=envoy-internal
    interval: 10m
    logLevel: &logLevel debug
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/crutonjohn/external-dns-opnsense-webhook
          tag: main@sha256:92bc3f6cedbc964a15902117f25ef42d87f74742ee9c4ed4900085d3edc56857
          pullPolicy: Always
        env:
          - name: OPNSENSE_API_KEY
            valueFrom:
              secretKeyRef:
                name: &secret opnsense-secrets
                key: opnsense_api_key
          - name: OPNSENSE_API_SECRET
            valueFrom:
              secretKeyRef:
                name: *secret
                key: opnsense_api_secret
          - name: OPNSENSE_HOST
            valueFrom:
              secretKeyRef:
                name: *secret
                key: opnsense_host
          - name: OPNSENSE_SKIP_TLS_VERIFY
            value: "true"
          - name: LOG_LEVEL
            value: *logLevel
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 128Mi
          requests:
            cpu: 8m
            memory: 128Mi
    registry: txt
    resources:
      limits:
        cpu: 2000m
        memory: 256Mi
      requests:
        cpu: 8m
        memory: 256Mi
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    sources:
      - gateway-httproute
      - service
    triggerLoopOnEvent: true
    txtOwnerId: k8s-internal
    txtPrefix: k8s-%{record_type}.
