apiVersion: v1
kind: Secret
metadata:
  name: opnsense-dns-secret
stringData:
  opnsense_api_key: ENC[AES256_GCM,data:wen+kA==,iv:j0Ixxwun5JtabSFsG+Oq9U4fRHG7Z6KxO6U7gRSjQ40=,tag:awcdN0qYLtsAV3R3Wnpqow==,type:str]
  opnsense_api_secret: ENC[AES256_GCM,data:wdVUNQ==,iv:bfD3iB/xK1gGIWtqdTjtlEV8B8jCO49iz6pGMCLbLns=,tag:dw1ztCK+a72ieAJY6/BnSg==,type:str]
  opnsense_host: ENC[AES256_GCM,data:GOEefL9IuXBcvTA=,iv:87PoBpGTP396Jf7IjsHRk6yVzzeWMzCLYCYaVHTZHUY=,tag:lc12AvvsrXXQURLmpfg/Yg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNWRCSk5mdkFnc3hHTXRp
        NlArdnUySHl3MWkrVEEva1hDb0ZZQnIrNkNnCjJzcGZJbk5sSm9uUmZIVjBVUjlt
        d3RtVWJ4VkdJVWZ3NXFWaUQxT29PZmMKLS0tIDRsWXlqcGQ3Y3Y5Qk1aY0pDWW9N
        RkFIdG8wMEduY0NIM0djS0hua1hjbnMK4Jfkl0kN2cyr5sePSC7I8VX4SN1MWkxE
        v0meXaOftOCf9zubifVTkLczImpd4R4U7Ipo1u3NqEtRYjDDdqr9nA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T13:27:38Z"
  mac: ENC[AES256_GCM,data:+Eg9Tet4N3Fr1PXKoaXlv3q8pTi/nCP/F7VBdc4gSrD+aMvrHbcnEnwRGDq6HDQVqkqRMo+6zdtSQLSPQ1+2i/RUj1NDVGlT3JtkRVhu/qVQ7JSzN3MSFSMzRr9QvXXXiZXtLSEzNhODw5u6aywbU1YlCCBkYwgT/RIuBJwHiuw=,iv:PizgWIHKIqQBTlr/sDJCbyfO/+R9N497ltnvpHgMEhk=,tag:3NtIELFA8A1MPcd6LUUfFQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
