apiVersion: v1
kind: Secret
metadata:
  name: opnsense-dns-secret
stringData:
  opnsense_api_key: ENC[AES256_GCM,data:BpKkQMi73piF/+dLUdNnVREgCugS9/BcFt3uphT1tez3GLFR0lwiRlHJ27c80tN4nhOXcQa+fWb68620T5sne49l3+QIWeTGj2kcFGh9ypA=,iv:c0Rakfsz3dOq8c7AasvySoI/Hf/Pyfh3B2+ah11opCk=,tag:zSjLlE+ipMFrgWxg3A2zaQ==,type:str]
  opnsense_api_secret: ENC[AES256_GCM,data:3Q99ehRd7F5OZATxXEbkBSBSYXf0ZrImhU9120UxCV8mEMNRulKHYt/OVby0SsTd736o5jnx96EzfdcsMKksKYDoBFQgV+/NLtoOw1lTEOY=,iv:vCDlSNHdA4ROlagSl+zwdiIb4VyMaygTHNrVpri5Gjw=,tag:WPKVnYGegOX37vLblZXQCA==,type:str]
  opnsense_host: ENC[AES256_GCM,data:tCNk0EPwWIIEZp3KB0aeVXV1VQ==,iv:yQuhPBkyZe929cmijjAtSXUqOfGdmkPFlBYVDIMSccc=,tag:WOU9t4pE4mANIX3wpGsGiQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaC9wQXluNWhTbWtUSU9s
        ZU45NnlyWlpBYlN3emsyUXk3SFdzSmdhQ3dnCnhsOEhQcEJWK0Q1dmd1cFBxZXZ0
        cWttNEhuOGQ0K29pUGtuV1FJOUdTb3cKLS0tIFM2ZXN2L2o3eHlNRGNUcS9KSndP
        U3hvd2R1cjNLSXRXTEoyZVZEUWhoR2MKmNw+7VoD5qyizEddRw8t09OLBuuRSOFw
        +8FE60q+VwVy1VxQO1SEsf4cbIJmYiD1pSCeB4ywKfiwm7tsnQuiFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1des8mkys7hfqrrasc2g6zrhcrvqxkmflgql08wpwfdvq0d89wa5s9fp4ww
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-27T13:38:53Z"
  mac: ENC[AES256_GCM,data:GugkJ3OSTCgVlYk+d60Q3W5cEoT1ZIwETrFgghAcrFnc8VnaKEvolzHqIFPfzib9hqyazMFtdTEau9/womttuX28KqWnOlWERVCpXmzc0oK/XrOje5Myvw5h1VYEa8jIgFWsLK2gowCVSHyDIpJHWFfTdX0j17zwKVPDBqOQGFo=,iv:Hd3aIPmKYmi12Eazcl9ioLEcgzVreaPCJ+pSaLf4Pdc=,tag:pcTI0Myi9vcb2v0y7bakgw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
